package net.minecraft.server;

public class SoundEffects {

    public static final SoundEffect a;
    public static final SoundEffect b;
    public static final SoundEffect c;
    public static final SoundEffect d;
    public static final SoundEffect e;
    public static final SoundEffect f;
    public static final SoundEffect g;
    public static final SoundEffect h;
    public static final SoundEffect i;
    public static final SoundEffect j;
    public static final SoundEffect k;
    public static final SoundEffect l;
    public static final SoundEffect m;
    public static final SoundEffect n;
    public static final SoundEffect o;
    public static final SoundEffect p;
    public static final SoundEffect q;
    public static final SoundEffect r;
    public static final SoundEffect s;
    public static final SoundEffect t;
    public static final SoundEffect u;
    public static final SoundEffect v;
    public static final SoundEffect w;
    public static final SoundEffect x;
    public static final SoundEffect y;
    public static final SoundEffect z;
    public static final SoundEffect A;
    public static final SoundEffect B;
    public static final SoundEffect C;
    public static final SoundEffect D;
    public static final SoundEffect E;
    public static final SoundEffect F;
    public static final SoundEffect G;
    public static final SoundEffect H;
    public static final SoundEffect I;
    public static final SoundEffect J;
    public static final SoundEffect K;
    public static final SoundEffect L;
    public static final SoundEffect M;
    public static final SoundEffect N;
    public static final SoundEffect O;
    public static final SoundEffect P;
    public static final SoundEffect Q;
    public static final SoundEffect R;
    public static final SoundEffect S;
    public static final SoundEffect T;
    public static final SoundEffect U;
    public static final SoundEffect V;
    public static final SoundEffect W;
    public static final SoundEffect X;
    public static final SoundEffect Y;
    public static final SoundEffect Z;
    public static final SoundEffect aa;
    public static final SoundEffect ab;
    public static final SoundEffect ac;
    public static final SoundEffect ad;
    public static final SoundEffect ae;
    public static final SoundEffect af;
    public static final SoundEffect ag;
    public static final SoundEffect ah;
    public static final SoundEffect ai;
    public static final SoundEffect aj;
    public static final SoundEffect ak;
    public static final SoundEffect al;
    public static final SoundEffect am;
    public static final SoundEffect an;
    public static final SoundEffect ao;
    public static final SoundEffect ap;
    public static final SoundEffect aq;
    public static final SoundEffect ar;
    public static final SoundEffect as;
    public static final SoundEffect at;
    public static final SoundEffect au;
    public static final SoundEffect av;
    public static final SoundEffect aw;
    public static final SoundEffect ax;
    public static final SoundEffect ay;
    public static final SoundEffect az;
    public static final SoundEffect aA;
    public static final SoundEffect aB;
    public static final SoundEffect aC;
    public static final SoundEffect aD;
    public static final SoundEffect aE;
    public static final SoundEffect aF;
    public static final SoundEffect aG;
    public static final SoundEffect aH;
    public static final SoundEffect aI;
    public static final SoundEffect aJ;
    public static final SoundEffect aK;
    public static final SoundEffect aL;
    public static final SoundEffect aM;
    public static final SoundEffect aN;
    public static final SoundEffect aO;
    public static final SoundEffect aP;
    public static final SoundEffect aQ;
    public static final SoundEffect aR;
    public static final SoundEffect aS;
    public static final SoundEffect aT;
    public static final SoundEffect aU;
    public static final SoundEffect aV;
    public static final SoundEffect aW;
    public static final SoundEffect aX;
    public static final SoundEffect aY;
    public static final SoundEffect aZ;
    public static final SoundEffect ba;
    public static final SoundEffect bb;
    public static final SoundEffect bc;
    public static final SoundEffect bd;
    public static final SoundEffect be;
    public static final SoundEffect bf;
    public static final SoundEffect bg;
    public static final SoundEffect bh;
    public static final SoundEffect bi;
    public static final SoundEffect bj;
    public static final SoundEffect bk;
    public static final SoundEffect bl;
    public static final SoundEffect bm;
    public static final SoundEffect bn;
    public static final SoundEffect bo;
    public static final SoundEffect bp;
    public static final SoundEffect bq;
    public static final SoundEffect br;
    public static final SoundEffect bs;
    public static final SoundEffect bt;
    public static final SoundEffect bu;
    public static final SoundEffect bv;
    public static final SoundEffect bw;
    public static final SoundEffect bx;
    public static final SoundEffect by;
    public static final SoundEffect bz;
    public static final SoundEffect bA;
    public static final SoundEffect bB;
    public static final SoundEffect bC;
    public static final SoundEffect bD;
    public static final SoundEffect bE;
    public static final SoundEffect bF;
    public static final SoundEffect bG;
    public static final SoundEffect bH;
    public static final SoundEffect bI;
    public static final SoundEffect bJ;
    public static final SoundEffect bK;
    public static final SoundEffect bL;
    public static final SoundEffect bM;
    public static final SoundEffect bN;
    public static final SoundEffect bO;
    public static final SoundEffect bP;
    public static final SoundEffect bQ;
    public static final SoundEffect bR;
    public static final SoundEffect bS;
    public static final SoundEffect bT;
    public static final SoundEffect bU;
    public static final SoundEffect bV;
    public static final SoundEffect bW;
    public static final SoundEffect bX;
    public static final SoundEffect bY;
    public static final SoundEffect bZ;
    public static final SoundEffect ca;
    public static final SoundEffect cb;
    public static final SoundEffect cc;
    public static final SoundEffect cd;
    public static final SoundEffect ce;
    public static final SoundEffect cf;
    public static final SoundEffect cg;
    public static final SoundEffect ch;
    public static final SoundEffect ci;
    public static final SoundEffect cj;
    public static final SoundEffect ck;
    public static final SoundEffect cl;
    public static final SoundEffect cm;
    public static final SoundEffect cn;
    public static final SoundEffect co;
    public static final SoundEffect cp;
    public static final SoundEffect cq;
    public static final SoundEffect cr;
    public static final SoundEffect cs;
    public static final SoundEffect ct;
    public static final SoundEffect cu;
    public static final SoundEffect cv;
    public static final SoundEffect cw;
    public static final SoundEffect cx;
    public static final SoundEffect cy;
    public static final SoundEffect cz;
    public static final SoundEffect cA;
    public static final SoundEffect cB;
    public static final SoundEffect cC;
    public static final SoundEffect cD;
    public static final SoundEffect cE;
    public static final SoundEffect cF;
    public static final SoundEffect cG;
    public static final SoundEffect cH;
    public static final SoundEffect cI;
    public static final SoundEffect cJ;
    public static final SoundEffect cK;
    public static final SoundEffect cL;
    public static final SoundEffect cM;
    public static final SoundEffect cN;
    public static final SoundEffect cO;
    public static final SoundEffect cP;
    public static final SoundEffect cQ;
    public static final SoundEffect cR;
    public static final SoundEffect cS;
    public static final SoundEffect cT;
    public static final SoundEffect cU;
    public static final SoundEffect cV;
    public static final SoundEffect cW;
    public static final SoundEffect cX;
    public static final SoundEffect cY;
    public static final SoundEffect cZ;
    public static final SoundEffect da;
    public static final SoundEffect db;
    public static final SoundEffect dc;
    public static final SoundEffect dd;
    public static final SoundEffect de;
    public static final SoundEffect df;
    public static final SoundEffect dg;
    public static final SoundEffect dh;
    public static final SoundEffect di;
    public static final SoundEffect dj;
    public static final SoundEffect dk;
    public static final SoundEffect dl;
    public static final SoundEffect dm;
    public static final SoundEffect dn;
    public static final SoundEffect do;
    public static final SoundEffect dp;
    public static final SoundEffect dq;
    public static final SoundEffect dr;
    public static final SoundEffect ds;
    public static final SoundEffect dt;
    public static final SoundEffect du;
    public static final SoundEffect dv;
    public static final SoundEffect dw;
    public static final SoundEffect BLOCK_METAL_PRESSUREPLATE_CLICK_OFF;
    public static final SoundEffect dy;
    public static final SoundEffect dz;
    public static final SoundEffect dA;
    public static final SoundEffect dB;
    public static final SoundEffect dC;
    public static final SoundEffect dD;
    public static final SoundEffect dE;
    public static final SoundEffect dF;
    public static final SoundEffect dG;
    public static final SoundEffect dH;
    public static final SoundEffect dI;
    public static final SoundEffect dJ;
    public static final SoundEffect dK;
    public static final SoundEffect dL;
    public static final SoundEffect dM;
    public static final SoundEffect dN;
    public static final SoundEffect dO;
    public static final SoundEffect dP;
    public static final SoundEffect dQ;
    public static final SoundEffect dR;
    public static final SoundEffect dS;
    public static final SoundEffect dT;
    public static final SoundEffect dU;
    public static final SoundEffect dV;
    public static final SoundEffect dW;
    public static final SoundEffect dX;
    public static final SoundEffect dY;
    public static final SoundEffect dZ;
    public static final SoundEffect ea;
    public static final SoundEffect eb;
    public static final SoundEffect ENTITY_PLAYER_ATTACK_CRIT;
    public static final SoundEffect ed;
    public static final SoundEffect ee;
    public static final SoundEffect ef;
    public static final SoundEffect eg;
    public static final SoundEffect eh;
    public static final SoundEffect ei;
    public static final SoundEffect ej;
    public static final SoundEffect ek;
    public static final SoundEffect el;
    public static final SoundEffect ENTITY_PLAYER_HURT;
    public static final SoundEffect en;
    public static final SoundEffect eo;
    public static final SoundEffect ep;
    public static final SoundEffect eq;
    public static final SoundEffect er;
    public static final SoundEffect es;
    public static final SoundEffect et;
    public static final SoundEffect eu;
    public static final SoundEffect ev;
    public static final SoundEffect ew;
    public static final SoundEffect ex;
    public static final SoundEffect ey;
    public static final SoundEffect ez;
    public static final SoundEffect eA;
    public static final SoundEffect eB;
    public static final SoundEffect eC;
    public static final SoundEffect eD;
    public static final SoundEffect eE;
    public static final SoundEffect eF;
    public static final SoundEffect eG;
    public static final SoundEffect eH;
    public static final SoundEffect eI;
    public static final SoundEffect eJ;
    public static final SoundEffect eK;
    public static final SoundEffect eL;
    public static final SoundEffect eM;
    public static final SoundEffect eN;
    public static final SoundEffect eO;
    public static final SoundEffect eP;
    public static final SoundEffect eQ;
    public static final SoundEffect eR;
    public static final SoundEffect eS;
    public static final SoundEffect eT;
    public static final SoundEffect eU;
    public static final SoundEffect eV;
    public static final SoundEffect eW;
    public static final SoundEffect eX;
    public static final SoundEffect eY;
    public static final SoundEffect eZ;
    public static final SoundEffect fa;
    public static final SoundEffect fb;
    public static final SoundEffect fc;
    public static final SoundEffect fd;
    public static final SoundEffect fe;
    public static final SoundEffect ff;
    public static final SoundEffect fg;
    public static final SoundEffect fh;
    public static final SoundEffect fi;
    public static final SoundEffect fj;
    public static final SoundEffect fk;
    public static final SoundEffect fl;
    public static final SoundEffect fm;
    public static final SoundEffect fn;
    public static final SoundEffect fo;
    public static final SoundEffect fp;
    public static final SoundEffect fq;
    public static final SoundEffect fr;
    public static final SoundEffect fs;
    public static final SoundEffect ft;
    public static final SoundEffect fu;
    public static final SoundEffect fv;
    public static final SoundEffect fw;
    public static final SoundEffect fx;
    public static final SoundEffect fy;
    public static final SoundEffect fz;
    public static final SoundEffect fA;
    public static final SoundEffect fB;
    public static final SoundEffect fC;
    public static final SoundEffect fD;
    public static final SoundEffect fE;
    public static final SoundEffect fF;
    public static final SoundEffect fG;
    public static final SoundEffect fH;
    public static final SoundEffect fI;
    public static final SoundEffect fJ;
    public static final SoundEffect fK;
    public static final SoundEffect fL;
    public static final SoundEffect fM;
    public static final SoundEffect fN;
    public static final SoundEffect fO;
    public static final SoundEffect fP;
    public static final SoundEffect fQ;
    public static final SoundEffect fR;
    public static final SoundEffect fS;
    public static final SoundEffect fT;
    public static final SoundEffect fU;
    public static final SoundEffect fV;
    public static final SoundEffect fW;
    public static final SoundEffect fX;
    public static final SoundEffect fY;
    public static final SoundEffect fZ;
    public static final SoundEffect ga;
    public static final SoundEffect gb;
    public static final SoundEffect gc;
    public static final SoundEffect gd;
    public static final SoundEffect ge;
    public static final SoundEffect gf;
    public static final SoundEffect gg;
    public static final SoundEffect gh;
    public static final SoundEffect gi;
    public static final SoundEffect gj;
    public static final SoundEffect gk;
    public static final SoundEffect gl;
    public static final SoundEffect gm;
    public static final SoundEffect gn;
    public static final SoundEffect go;
    public static final SoundEffect gp;
    public static final SoundEffect gq;
    public static final SoundEffect gr;
    public static final SoundEffect gs;
    public static final SoundEffect gt;
    public static final SoundEffect gu;
    public static final SoundEffect gv;
    public static final SoundEffect gw;
    public static final SoundEffect gx;
    public static final SoundEffect gy;
    public static final SoundEffect gz;
    public static final SoundEffect gA;
    public static final SoundEffect gB;
    public static final SoundEffect gC;
    public static final SoundEffect gD;
    public static final SoundEffect gE;
    public static final SoundEffect gF;
    public static final SoundEffect gG;
    public static final SoundEffect gH;
    public static final SoundEffect gI;
    public static final SoundEffect gJ;
    public static final SoundEffect gK;
    public static final SoundEffect gL;
    public static final SoundEffect gM;
    public static final SoundEffect gN;
    public static final SoundEffect gO;
    public static final SoundEffect gP;
    public static final SoundEffect gQ;
    public static final SoundEffect gR;
    public static final SoundEffect gS;
    public static final SoundEffect gT;
    public static final SoundEffect gU;
    public static final SoundEffect gV;
    public static final SoundEffect gW;
    public static final SoundEffect gX;
    public static final SoundEffect gY;
    public static final SoundEffect gZ;
    public static final SoundEffect ha;
    public static final SoundEffect hb;
    public static final SoundEffect hc;
    public static final SoundEffect hd;
    public static final SoundEffect he;
    public static final SoundEffect hf;
    public static final SoundEffect hg;
    public static final SoundEffect hh;
    public static final SoundEffect hi;
    public static final SoundEffect hj;
    public static final SoundEffect hk;
    public static final SoundEffect hl;
    public static final SoundEffect hm;
    public static final SoundEffect hn;
    public static final SoundEffect ho;
    public static final SoundEffect hp;
    public static final SoundEffect hq;
    public static final SoundEffect hr;
    public static final SoundEffect hs;
    public static final SoundEffect ht;
    public static final SoundEffect hu;
    public static final SoundEffect hv;
    public static final SoundEffect hw;
    public static final SoundEffect hx;
    public static final SoundEffect hy;
    public static final SoundEffect hz;
    public static final SoundEffect hA;
    public static final SoundEffect hB;
    public static final SoundEffect hC;
    public static final SoundEffect hD;
    public static final SoundEffect hE;
    public static final SoundEffect hF;
    public static final SoundEffect hG;
    public static final SoundEffect hH;
    public static final SoundEffect hI;
    public static final SoundEffect hJ;
    public static final SoundEffect hK;
    public static final SoundEffect hL;
    public static final SoundEffect hM;
    public static final SoundEffect hN;
    public static final SoundEffect hO;
    public static final SoundEffect hP;
    public static final SoundEffect hQ;
    public static final SoundEffect hR;
    public static final SoundEffect hS;
    public static final SoundEffect hT;
    public static final SoundEffect hU;

    private static SoundEffect a(String s) {
        SoundEffect soundeffect = (SoundEffect) SoundEffect.a.get(new MinecraftKey(s));

        if (soundeffect == null) {
            throw new IllegalStateException("Invalid Sound requested: " + s);
        } else {
            return soundeffect;
        }
    }

    static {
        if (!DispenserRegistry.a()) {
            throw new RuntimeException("Accessed Sounds before Bootstrap!");
        } else {
            a = a("ambient.cave");
            b = a("block.anvil.break");
            c = a("block.anvil.destroy");
            d = a("block.anvil.fall");
            e = a("block.anvil.hit");
            f = a("block.anvil.land");
            g = a("block.anvil.place");
            h = a("block.anvil.step");
            i = a("block.anvil.use");
            j = a("entity.armorstand.break");
            k = a("entity.armorstand.fall");
            l = a("entity.armorstand.hit");
            m = a("entity.armorstand.place");
            n = a("item.armor.equip_chain");
            o = a("item.armor.equip_diamond");
            p = a("item.armor.equip_generic");
            q = a("item.armor.equip_gold");
            r = a("item.armor.equip_iron");
            s = a("item.armor.equip_leather");
            t = a("entity.arrow.hit");
            u = a("entity.arrow.hit_player");
            v = a("entity.arrow.shoot");
            w = a("entity.bat.ambient");
            x = a("entity.bat.death");
            y = a("entity.bat.hurt");
            z = a("entity.bat.loop");
            A = a("entity.bat.takeoff");
            B = a("entity.blaze.ambient");
            C = a("entity.blaze.burn");
            D = a("entity.blaze.death");
            E = a("entity.blaze.hurt");
            F = a("entity.blaze.shoot");
            G = a("entity.bobber.splash");
            H = a("entity.bobber.throw");
            I = a("item.bottle.fill");
            J = a("item.bottle.fill_dragonbreath");
            K = a("block.brewing_stand.brew");
            L = a("item.bucket.empty");
            M = a("item.bucket.empty_lava");
            N = a("item.bucket.fill");
            O = a("item.bucket.fill_lava");
            P = a("entity.cat.ambient");
            Q = a("entity.cat.death");
            R = a("entity.cat.hiss");
            S = a("entity.cat.hurt");
            T = a("entity.cat.purr");
            U = a("entity.cat.purreow");
            V = a("block.chest.close");
            W = a("block.chest.locked");
            X = a("block.chest.open");
            Y = a("entity.chicken.ambient");
            Z = a("entity.chicken.death");
            aa = a("entity.chicken.egg");
            ab = a("entity.chicken.hurt");
            ac = a("entity.chicken.step");
            ad = a("block.chorus_flower.death");
            ae = a("block.chorus_flower.grow");
            af = a("item.chorus_fruit.teleport");
            ag = a("block.cloth.break");
            ah = a("block.cloth.fall");
            ai = a("block.cloth.hit");
            aj = a("block.cloth.place");
            ak = a("block.cloth.step");
            al = a("block.comparator.click");
            am = a("entity.cow.ambient");
            an = a("entity.cow.death");
            ao = a("entity.cow.hurt");
            ap = a("entity.cow.milk");
            aq = a("entity.cow.step");
            ar = a("entity.creeper.death");
            as = a("entity.creeper.hurt");
            at = a("entity.creeper.primed");
            au = a("block.dispenser.dispense");
            av = a("block.dispenser.fail");
            aw = a("block.dispenser.launch");
            ax = a("entity.donkey.ambient");
            ay = a("entity.donkey.angry");
            az = a("entity.donkey.chest");
            aA = a("entity.donkey.death");
            aB = a("entity.donkey.hurt");
            aC = a("entity.egg.throw");
            aD = a("entity.elder_guardian.ambient");
            aE = a("entity.elder_guardian.ambient_land");
            aF = a("entity.elder_guardian.curse");
            aG = a("entity.elder_guardian.death");
            aH = a("entity.elder_guardian.death_land");
            aI = a("entity.elder_guardian.hurt");
            aJ = a("entity.elder_guardian.hurt_land");
            aK = a("item.elytra.flying");
            aL = a("block.enchantment_table.use");
            aM = a("block.enderchest.close");
            aN = a("block.enderchest.open");
            aO = a("entity.enderdragon.ambient");
            aP = a("entity.enderdragon.death");
            aQ = a("entity.enderdragon_fireball.explode");
            aR = a("entity.enderdragon.flap");
            aS = a("entity.enderdragon.growl");
            aT = a("entity.enderdragon.hurt");
            aU = a("entity.enderdragon.shoot");
            aV = a("entity.endereye.launch");
            aW = a("entity.endermen.ambient");
            aX = a("entity.endermen.death");
            aY = a("entity.endermen.hurt");
            aZ = a("entity.endermen.scream");
            ba = a("entity.endermen.stare");
            bb = a("entity.endermen.teleport");
            bc = a("entity.endermite.ambient");
            bd = a("entity.endermite.death");
            be = a("entity.endermite.hurt");
            bf = a("entity.endermite.step");
            bg = a("entity.enderpearl.throw");
            bh = a("block.end_gateway.spawn");
            bi = a("entity.experience_bottle.throw");
            bj = a("entity.experience_orb.pickup");
            bk = a("entity.experience_orb.touch");
            bl = a("block.fence_gate.close");
            bm = a("block.fence_gate.open");
            bn = a("item.firecharge.use");
            bo = a("entity.firework.blast");
            bp = a("entity.firework.blast_far");
            bq = a("entity.firework.large_blast");
            br = a("entity.firework.large_blast_far");
            bs = a("entity.firework.launch");
            bt = a("entity.firework.shoot");
            bu = a("entity.firework.twinkle");
            bv = a("entity.firework.twinkle_far");
            bw = a("block.fire.ambient");
            bx = a("block.fire.extinguish");
            by = a("item.flintandsteel.use");
            bz = a("block.furnace.fire_crackle");
            bA = a("entity.generic.big_fall");
            bB = a("entity.generic.burn");
            bC = a("entity.generic.death");
            bD = a("entity.generic.drink");
            bE = a("entity.generic.eat");
            bF = a("entity.generic.explode");
            bG = a("entity.generic.extinguish_fire");
            bH = a("entity.generic.hurt");
            bI = a("entity.generic.small_fall");
            bJ = a("entity.generic.splash");
            bK = a("entity.generic.swim");
            bL = a("entity.ghast.ambient");
            bM = a("entity.ghast.death");
            bN = a("entity.ghast.hurt");
            bO = a("entity.ghast.scream");
            bP = a("entity.ghast.shoot");
            bQ = a("entity.ghast.warn");
            bR = a("block.glass.break");
            bS = a("block.glass.fall");
            bT = a("block.glass.hit");
            bU = a("block.glass.place");
            bV = a("block.glass.step");
            bW = a("block.grass.break");
            bX = a("block.grass.fall");
            bY = a("block.grass.hit");
            bZ = a("block.grass.place");
            ca = a("block.grass.step");
            cb = a("block.gravel.break");
            cc = a("block.gravel.fall");
            cd = a("block.gravel.hit");
            ce = a("block.gravel.place");
            cf = a("block.gravel.step");
            cg = a("entity.guardian.ambient");
            ch = a("entity.guardian.ambient_land");
            ci = a("entity.guardian.attack");
            cj = a("entity.guardian.death");
            ck = a("entity.guardian.death_land");
            cl = a("entity.guardian.flop");
            cm = a("entity.guardian.hurt");
            cn = a("entity.guardian.hurt_land");
            co = a("item.hoe.till");
            cp = a("entity.horse.ambient");
            cq = a("entity.horse.angry");
            cr = a("entity.horse.armor");
            cs = a("entity.horse.breathe");
            ct = a("entity.horse.death");
            cu = a("entity.horse.eat");
            cv = a("entity.horse.gallop");
            cw = a("entity.horse.hurt");
            cx = a("entity.horse.jump");
            cy = a("entity.horse.land");
            cz = a("entity.horse.saddle");
            cA = a("entity.horse.step");
            cB = a("entity.horse.step_wood");
            cC = a("entity.hostile.big_fall");
            cD = a("entity.hostile.death");
            cE = a("entity.hostile.hurt");
            cF = a("entity.hostile.small_fall");
            cG = a("entity.hostile.splash");
            cH = a("entity.hostile.swim");
            cI = a("entity.husk.ambient");
            cJ = a("entity.husk.death");
            cK = a("entity.husk.hurt");
            cL = a("entity.husk.step");
            cM = a("entity.irongolem.attack");
            cN = a("entity.irongolem.death");
            cO = a("entity.irongolem.hurt");
            cP = a("entity.irongolem.step");
            cQ = a("block.iron_door.close");
            cR = a("block.iron_door.open");
            cS = a("block.iron_trapdoor.close");
            cT = a("block.iron_trapdoor.open");
            cU = a("entity.itemframe.add_item");
            cV = a("entity.itemframe.break");
            cW = a("entity.itemframe.place");
            cX = a("entity.itemframe.remove_item");
            cY = a("entity.itemframe.rotate_item");
            cZ = a("entity.item.break");
            da = a("entity.item.pickup");
            db = a("block.ladder.break");
            dc = a("block.ladder.fall");
            dd = a("block.ladder.hit");
            de = a("block.ladder.place");
            df = a("block.ladder.step");
            dg = a("block.lava.ambient");
            dh = a("block.lava.extinguish");
            di = a("block.lava.pop");
            dj = a("entity.leashknot.break");
            dk = a("entity.leashknot.place");
            dl = a("block.lever.click");
            dm = a("entity.lightning.impact");
            dn = a("entity.lightning.thunder");
            do = a("entity.lingeringpotion.throw");
            dp = a("entity.magmacube.death");
            dq = a("entity.magmacube.hurt");
            dr = a("entity.magmacube.jump");
            ds = a("entity.magmacube.squish");
            dt = a("block.metal.break");
            du = a("block.metal.fall");
            dv = a("block.metal.hit");
            dw = a("block.metal.place");
            BLOCK_METAL_PRESSUREPLATE_CLICK_OFF = a("block.metal_pressureplate.click_off");
            dy = a("block.metal_pressureplate.click_on");
            dz = a("block.metal.step");
            dA = a("entity.minecart.inside");
            dB = a("entity.minecart.riding");
            dC = a("entity.mooshroom.shear");
            dD = a("entity.mule.ambient");
            dE = a("entity.mule.death");
            dF = a("entity.mule.hurt");
            dG = a("music.creative");
            dH = a("music.credits");
            dI = a("music.dragon");
            dJ = a("music.end");
            dK = a("music.game");
            dL = a("music.menu");
            dM = a("music.nether");
            dN = a("block.note.basedrum");
            dO = a("block.note.bass");
            dP = a("block.note.harp");
            dQ = a("block.note.hat");
            dR = a("block.note.pling");
            dS = a("block.note.snare");
            dT = a("entity.painting.break");
            dU = a("entity.painting.place");
            dV = a("entity.pig.ambient");
            dW = a("entity.pig.death");
            dX = a("entity.pig.hurt");
            dY = a("entity.pig.saddle");
            dZ = a("entity.pig.step");
            ea = a("block.piston.contract");
            eb = a("block.piston.extend");
            ENTITY_PLAYER_ATTACK_CRIT = a("entity.player.attack.crit");
            ed = a("entity.player.attack.knockback");
            ee = a("entity.player.attack.nodamage");
            ef = a("entity.player.attack.strong");
            eg = a("entity.player.attack.sweep");
            eh = a("entity.player.attack.weak");
            ei = a("entity.player.big_fall");
            ej = a("entity.player.breath");
            ek = a("entity.player.burp");
            el = a("entity.player.death");
            ENTITY_PLAYER_HURT = a("entity.player.hurt");
            en = a("entity.player.levelup");
            eo = a("entity.player.small_fall");
            ep = a("entity.player.splash");
            eq = a("entity.player.swim");
            er = a("entity.polar_bear.ambient");
            es = a("entity.polar_bear.baby_ambient");
            et = a("entity.polar_bear.death");
            eu = a("entity.polar_bear.hurt");
            ev = a("entity.polar_bear.step");
            ew = a("entity.polar_bear.warning");
            ex = a("block.portal.ambient");
            ey = a("block.portal.travel");
            ez = a("block.portal.trigger");
            eA = a("entity.rabbit.ambient");
            eB = a("entity.rabbit.attack");
            eC = a("entity.rabbit.death");
            eD = a("entity.rabbit.hurt");
            eE = a("entity.rabbit.jump");
            eF = a("record.11");
            eG = a("record.13");
            eH = a("record.blocks");
            eI = a("record.cat");
            eJ = a("record.chirp");
            eK = a("record.far");
            eL = a("record.mall");
            eM = a("record.mellohi");
            eN = a("record.stal");
            eO = a("record.strad");
            eP = a("record.wait");
            eQ = a("record.ward");
            eR = a("block.redstone_torch.burnout");
            eS = a("block.sand.break");
            eT = a("block.sand.fall");
            eU = a("block.sand.hit");
            eV = a("block.sand.place");
            eW = a("block.sand.step");
            eX = a("entity.sheep.ambient");
            eY = a("entity.sheep.death");
            eZ = a("entity.sheep.hurt");
            fa = a("entity.sheep.shear");
            fb = a("entity.sheep.step");
            fc = a("item.shield.block");
            fd = a("item.shield.break");
            fe = a("item.shovel.flatten");
            ff = a("entity.shulker.ambient");
            fg = a("entity.shulker_bullet.hit");
            fh = a("entity.shulker_bullet.hurt");
            fi = a("entity.shulker.close");
            fj = a("entity.shulker.death");
            fk = a("entity.shulker.hurt");
            fl = a("entity.shulker.hurt_closed");
            fm = a("entity.shulker.open");
            fn = a("entity.shulker.shoot");
            fo = a("entity.shulker.teleport");
            fp = a("entity.silverfish.ambient");
            fq = a("entity.silverfish.death");
            fr = a("entity.silverfish.hurt");
            fs = a("entity.silverfish.step");
            ft = a("entity.skeleton.ambient");
            fu = a("entity.skeleton.death");
            fv = a("entity.skeleton_horse.ambient");
            fw = a("entity.skeleton_horse.death");
            fx = a("entity.skeleton_horse.hurt");
            fy = a("entity.skeleton.hurt");
            fz = a("entity.skeleton.shoot");
            fA = a("entity.skeleton.step");
            fB = a("entity.slime.attack");
            fC = a("block.slime.break");
            fD = a("entity.slime.death");
            fE = a("block.slime.fall");
            fF = a("block.slime.hit");
            fG = a("entity.slime.hurt");
            fH = a("entity.slime.jump");
            fI = a("block.slime.place");
            fJ = a("entity.slime.squish");
            fK = a("block.slime.step");
            fL = a("entity.small_magmacube.death");
            fM = a("entity.small_magmacube.hurt");
            fN = a("entity.small_magmacube.squish");
            fO = a("entity.small_slime.death");
            fP = a("entity.small_slime.hurt");
            fQ = a("entity.small_slime.jump");
            fR = a("entity.small_slime.squish");
            fS = a("entity.snowball.throw");
            fT = a("entity.snowman.ambient");
            fU = a("entity.snowman.death");
            fV = a("entity.snowman.hurt");
            fW = a("entity.snowman.shoot");
            fX = a("block.snow.break");
            fY = a("block.snow.fall");
            fZ = a("block.snow.hit");
            ga = a("block.snow.place");
            gb = a("block.snow.step");
            gc = a("entity.spider.ambient");
            gd = a("entity.spider.death");
            ge = a("entity.spider.hurt");
            gf = a("entity.spider.step");
            gg = a("entity.splash_potion.break");
            gh = a("entity.splash_potion.throw");
            gi = a("entity.squid.ambient");
            gj = a("entity.squid.death");
            gk = a("entity.squid.hurt");
            gl = a("block.stone.break");
            gm = a("block.stone_button.click_off");
            gn = a("block.stone_button.click_on");
            go = a("block.stone.fall");
            gp = a("block.stone.hit");
            gq = a("block.stone.place");
            gr = a("block.stone_pressureplate.click_off");
            gs = a("block.stone_pressureplate.click_on");
            gt = a("block.stone.step");
            gu = a("entity.stray.ambient");
            gv = a("entity.stray.death");
            gw = a("entity.stray.hurt");
            gx = a("entity.stray.step");
            gy = a("enchant.thorns.hit");
            gz = a("entity.tnt.primed");
            gA = a("block.tripwire.attach");
            gB = a("block.tripwire.click_off");
            gC = a("block.tripwire.click_on");
            gD = a("block.tripwire.detach");
            gE = a("ui.button.click");
            gF = a("entity.villager.ambient");
            gG = a("entity.villager.death");
            gH = a("entity.villager.hurt");
            gI = a("entity.villager.no");
            gJ = a("entity.villager.trading");
            gK = a("entity.villager.yes");
            gL = a("block.waterlily.place");
            gM = a("block.water.ambient");
            gN = a("weather.rain");
            gO = a("weather.rain.above");
            gP = a("entity.witch.ambient");
            gQ = a("entity.witch.death");
            gR = a("entity.witch.drink");
            gS = a("entity.witch.hurt");
            gT = a("entity.witch.throw");
            gU = a("entity.wither.ambient");
            gV = a("entity.wither.break_block");
            gW = a("entity.wither.death");
            gX = a("entity.wither.hurt");
            gY = a("entity.wither.shoot");
            gZ = a("entity.wither.spawn");
            ha = a("entity.wither_skeleton.ambient");
            hb = a("entity.wither_skeleton.death");
            hc = a("entity.wither_skeleton.hurt");
            hd = a("entity.wither_skeleton.step");
            he = a("entity.wolf.ambient");
            hf = a("entity.wolf.death");
            hg = a("entity.wolf.growl");
            hh = a("entity.wolf.howl");
            hi = a("entity.wolf.hurt");
            hj = a("entity.wolf.pant");
            hk = a("entity.wolf.shake");
            hl = a("entity.wolf.step");
            hm = a("entity.wolf.whine");
            hn = a("block.wooden_door.close");
            ho = a("block.wooden_door.open");
            hp = a("block.wooden_trapdoor.close");
            hq = a("block.wooden_trapdoor.open");
            hr = a("block.wood.break");
            hs = a("block.wood_button.click_off");
            ht = a("block.wood_button.click_on");
            hu = a("block.wood.fall");
            hv = a("block.wood.hit");
            hw = a("block.wood.place");
            hx = a("block.wood_pressureplate.click_off");
            hy = a("block.wood_pressureplate.click_on");
            hz = a("block.wood.step");
            hA = a("entity.zombie.ambient");
            hB = a("entity.zombie.attack_door_wood");
            hC = a("entity.zombie.attack_iron_door");
            hD = a("entity.zombie.break_door_wood");
            hE = a("entity.zombie.death");
            hF = a("entity.zombie_horse.ambient");
            hG = a("entity.zombie_horse.death");
            hH = a("entity.zombie_horse.hurt");
            hI = a("entity.zombie.hurt");
            hJ = a("entity.zombie.infect");
            hK = a("entity.zombie_pig.ambient");
            hL = a("entity.zombie_pig.angry");
            hM = a("entity.zombie_pig.death");
            hN = a("entity.zombie_pig.hurt");
            hO = a("entity.zombie.step");
            hP = a("entity.zombie_villager.ambient");
            hQ = a("entity.zombie_villager.converted");
            hR = a("entity.zombie_villager.cure");
            hS = a("entity.zombie_villager.death");
            hT = a("entity.zombie_villager.hurt");
            hU = a("entity.zombie_villager.step");
        }
    }
}
